### ISSUE TITLE
Project status. 

### ISSUE THREAD

**Issue by struktured** [gaiustech/ociml#2]
Are you still managing this project (and cohml)? Will you accept pull requests? I have a couple bug fixes for nullable columns. 

Finally, I am interested in making this an official opam package. Let me know your plans for these projects so I can coordinate accordingly.

Thanks

**Comment by gaiustech** [comment]
Hi,


Yes I am and would be happy to accept such a request! My current employer unfortunately claims ownership of any IP I create so I have been reluctant to work on it recently but I am sure accepting work from others wouldn't fall under that.


Thanks,


Gaius



From: Carmelo Piccione
Sent: Thursday, 4 June 2015 18:18
To: gaiustech/ociml
Reply To: gaiustech/ociml
Subject: [ociml] Project status. (#2)


Are you still managing this project (and cohml)? Will you accept pull requests? I have a couple bug fixes for nullable columns.

Finally, I am interested in making this an official opam package. Let me know your plans for these projects so I can coordinate accordingly.

Thanks


---
Reply to this email directly or view it on GitHub:
https://github.com/gaiustech/ociml/issues/2

**Comment by struktured** [comment]
That's unfortunate about the IP thing, but it's good news that contributions are still on the table. I will submit a PR after cleaning up the code a bit. Thanks!
